service: smsbeacon

provider:
  name: aws
  runtime: python3.6
  stage: production

plugins:
  - serverless-wsgi

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY {proxy+}
      - http: ANY /
    #call_process:
      #handler: call_process.handler
      #events:
        #- schedule: rate(1 minute)

custom:
  wsgi:
    app: app.app

package:
  exclude:
    - '.git/**'
    - '__pycache__/**'
    - '*.txt'
    - '*.md'
