service: smsbeacon_dev

provider:
  name: aws
  runtime: python3.6

plugins:
  - serverless-wsgi
  - serverless-python-requirements

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY {proxy+}
      - http: ANY /

custom:
  wsgi:
    app: app.app
